/**
 * Playwright scraping source — LEGAL skill demonstration.
 *
 * Proves the same end-to-end skill the mission asks for (browser automation →
 * DOM extraction → structured data) WITHOUT touching a third party: it serves a
 * local mock rental marketplace (generated by fixtures/build-mock-site.ts) over
 * HTTP, then drives real headless Chromium to crawl the index and scrape each
 * listing page. Repoint `BASE`/selectors at any site you're permitted to scrape
 * (a scraping sandbox, or a licensed feed) and the rest of the pipeline is
 * unchanged. No anti-bot evasion, no proxies, no guest data.
 */
import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';
import { chromium } from 'playwright';
import type { ListingSource, SourceListing, PublicReview, HostBusinessContact } from '../types';
import { createLogger } from '../../utils/logger';

const log = createLogger('source.mock-scrape');
const SITE_DIR = path.resolve(__dirname, '..', 'fixtures', 'mock-site');

/** Minimal static file server (127.0.0.1, ephemeral port) for the mock site. */
function startStaticServer(dir: string): Promise<{ port: number; close: () => Promise<void> }> {
  return new Promise((resolve, reject) => {
    const server = http.createServer((req, res) => {
      const reqPath = decodeURIComponent((req.url ?? '/').split('?')[0]);
      const rel = path.normalize(reqPath).replace(/^([/\\])+/, '').replace(/\.\.[/\\]/g, '');
      const file = path.join(dir, rel === '' ? 'index.html' : rel);
      if (!file.startsWith(dir)) { res.statusCode = 403; res.end('forbidden'); return; }
      fs.readFile(file, (err, buf) => {
        if (err) { res.statusCode = 404; res.end('not found'); return; }
        res.setHeader('Content-Type', 'text/html; charset=utf-8');
        res.end(buf);
      });
    });
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const addr = server.address();
      const port = typeof addr === 'object' && addr ? addr.port : 0;
      resolve({ port, close: () => new Promise<void>((r) => server.close(() => r())) });
    });
  });
}

const clean = (v: unknown): string | undefined => {
  const s = typeof v === 'string' ? v.trim() : '';
  return s ? s : undefined;
};
const num = (v: unknown): number | undefined => {
  const n = Number(v);
  return Number.isFinite(n) ? n : undefined;
};

export class MockScrapeSource implements ListingSource {
  readonly name = 'mock';

  async fetchListings(opts: { limit?: number } = {}): Promise<SourceListing[]> {
    const srv = await startStaticServer(SITE_DIR);
    const base = `http://127.0.0.1:${srv.port}`;
    log.info('Serving mock marketplace + launching headless Chromium', { base });

    const browser = await chromium.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-dev-shm-usage'],
    });

    try {
      const page = await browser.newPage();

      // 1) Crawl the index page to discover listing URLs.
      await page.goto(`${base}/index.html`, { waitUntil: 'domcontentloaded', timeout: 30_000 });
      let hrefs: string[] = await page.$$eval('.listing-link', (els: any) =>
        (els as any[]).map((e) => e.getAttribute('href')).filter(Boolean));
      if (opts.limit) hrefs = hrefs.slice(0, opts.limit);
      log.info('Discovered listing pages from the index', { count: hrefs.length });

      // 2) Visit each listing page and extract structured data from the DOM.
      const out: SourceListing[] = [];
      for (const href of hrefs) {
        await page.goto(`${base}/${href}`, { waitUntil: 'domcontentloaded', timeout: 30_000 });
        await page.waitForSelector('.listing', { timeout: 10_000 });
        const raw = await page.evaluate(() => {
          const d: any = (globalThis as any).document;
          const q = (sel: string): any => d.querySelector(sel);
          const at = (el: any, name: string): string | null => (el ? el.getAttribute(name) : null);
          const text = (sel: string): string => (q(sel)?.textContent ?? '').trim();
          const reviews = Array.from(d.querySelectorAll('.review')).map((r: any) => ({
            text:   (r.querySelector('.review-text')?.textContent ?? '').trim(),
            rating: r.getAttribute('data-rating'),
            date:   r.getAttribute('data-date'),
          }));
          return {
            id:           at(q('.listing'), 'data-id'),
            platform:     at(q('.listing'), 'data-platform'),
            title:        text('.title'),
            city:         at(q('.location'), 'data-city'),
            country:      at(q('.location'), 'data-country'),
            rating:       at(q('.rating'), 'data-rating'),
            reviewsCount: at(q('.rating'), 'data-reviews-count'),
            superhost:    at(q('.superhost'), 'data-superhost'),
            host: {
              hostName:          text('.host-name'),
              managementCompany: text('.host-company'),
              businessWebsite:   at(q('.host-website'), 'href'),
              businessEmail:     text('.host-email'),
              businessPhone:     text('.host-phone'),
              companyLinkedIn:   at(q('.host-linkedin'), 'href'),
            },
            reviews,
          };
        });
        out.push(this.toListing(raw));
      }

      log.info('Scraped listings via Playwright', { count: out.length });
      return out;
    } finally {
      await browser.close();
      await srv.close();
    }
  }

  private toListing(raw: any): SourceListing {
    const reviews: PublicReview[] = (raw.reviews ?? [])
      .map((r: any) => ({ text: String(r.text ?? ''), rating: num(r.rating), date: clean(r.date) }))
      .filter((r: PublicReview) => r.text);

    const host: HostBusinessContact = {
      hostName:          clean(raw.host?.hostName),
      managementCompany: clean(raw.host?.managementCompany),
      businessWebsite:   clean(raw.host?.businessWebsite),
      businessEmail:     clean(raw.host?.businessEmail),
      businessPhone:     clean(raw.host?.businessPhone),
      companyLinkedIn:   clean(raw.host?.companyLinkedIn),
    };

    return {
      id:           clean(raw.id) ?? `mock-${Math.random().toString(36).slice(2)}`,
      platform:     clean(raw.platform) ?? 'mock',
      title:        clean(raw.title) ?? 'Untitled listing',
      city:         clean(raw.city),
      country:      clean(raw.country),
      rating:       num(raw.rating),
      reviewsCount: num(raw.reviewsCount),
      isSuperhost:  raw.superhost === 'true' ? true : raw.superhost === 'false' ? false : undefined,
      reviews,
      host,
    };
  }
}
